### ISSUE TITLE
Handle new circuit that supports amount > 2**63

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1017]
See https://github.com/EspressoSystems/cap/issues/37

- [ ] Point this repository to latest version of Jellyfish
- [ ] Regenerate the smart contract code corresponding to the new plonk verifying keys. See See https://github.com/EspressoSystems/cap/issues/37#issuecomment-1134733906 fo
- [ ] Test that ensures amount > 2**63 can be handled

**Comment by sveitser** [comment]
@jbearer @shenkeyao In order to update `jf-cap` to 0.0.4 I think I also need to update our seahorse version to track the same version of `jf-cap`. This leads to a bunch of updates for espresso dependencies. It looks like they are already on the main branch on seahorse but that one is tracking the `testnet-v1` branch of `cap`. In this repo we are tracking the `release-0.2` of seahorse.

Should the changes on the main branch of `seahorse` be ported to `release-0.2`? Or should we start tracking `testnet-v1` of `cap` as well? Or is there a better solution?

**Comment by sveitser** [comment]
@jbearer I'm working using the `jeb-amount` branch from https://github.com/EspressoSystems/seahorse/pull/169. This includes quite a lot of changes from u64 to u128 / `Amount` in the wallet code. Two questions.

1. Is it okay if I do this as part of this Issue? I don't think it's feasible to do either the contract or the wallet in isolation for this change.
2. What's the intended use case for the new seahorse `RecordAmount` vs the `Amount` type?
