### ISSUE TITLE
Remaining TODO in README.md

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#709]
There is a TODO related to the CI in README.md:

https://github.com/EspressoSystems/cape#ci

**Comment by sveitser** [comment]
I added the TODO. @Ancient123 Do you know if there is a convenient way to do a github CI run locally? There is https://github.com/nektos/act that provides something in that direction.

**Comment by Ancient123** [comment]
I will dig into act. It looks like good tooling for this. Generally speaking, I try to avoid the "make CI run locally" goal since it tends to be large work for little reward. Especially if you are using the CI specific tooling.

Most of the issues people think this is gonna solve (local build inconsistencies) aren't actually helped by doing this since it still gets effected by the local environment (things like base system architecture and OS shenanigans).

My old solution to this was doing `dockerfile` based builds in CI. But that removes a bunch of convenience factors of actually using features of the CI system (like cacheing, reporting tabs, and automatic comments on PRs)

**Comment by philippecamacho** [comment]
@Ancient123 act does not work in our repositories.

Remove TODO in the README.md.
Put reference to "run-ci-tests" script instead.

**Comment by philippecamacho** [comment]
Done in #824.
