### ISSUE TITLE
Integration test(s) corresponding to the GUI script

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#786]
See https://www.notion.so/espressosys/bacd568c26da4cdc93e32bffb68b7916?v=298eaf75be5946fc97311f7de9537f72

- [x]  review the script and give feedback
- [x] plan  integration tests

**Comment by philippecamacho** [comment]
We need to the GUI test script.

**Comment by pictographer** [comment]
The Cape UI code has [wrappers](https://github.com/EspressoSystems/cape-ui/tree/dev/src/api) around the wallet routes. Routes are fetched with a function serverRequest() defined in this directory in `serverRequest.ts`. The integration tests should exercise all the routes listed below. I don't know yet if the Cape UI uses all of these routes, but I do know it does not use any wallet routes not listed here.

Most of the routes currently listed in the code are simple. 
- [ ] /closewallet
- [ ] /freeze/${address}/${asset}/fee/${feeAddress}/${feeAmount}
- [ ] /getaccount/${address}
- [ ] /getaddress
- [ ] /getbalance/address/${address}
- [ ] /getbalance/address/${address}/asset/${asset}
- [ ] /getbalance/all
- [ ] /getmnemonic
- [ ] /importkey/${type}/${key}
- [ ] /importkey/${type}/${key}
- [ ] /importkey/${type}/${key}/${index}
- [ ] /importkey/${type}/${key}/${index}
- [ ] /lastusedkeystore
- [ ] /listkeystores
- [ ] /mint/asset/${asset}/amount/${amount}/sendkey/${sendKey}/freezekey/${freezeKey}/tracekey/${traceKey}
- [ ] /newkey/${type}
- [ ] /newwallet/${mnemonic}/${password}
- [ ] /newwallet/${mnemonic}/${password}/name/${name}
- [ ] /openwallet/${password}
- [ ] /openwallet/${password}/name/${name}
- [ ] /resetpassword/${mnemonic}/${password}
- [ ] /resetpassword/${mnemonic}/${password}/name/${name}
- [ ] /send/sender/${sender}/asset/${asset}/recipient/${recipient}/amount/${amount}/fee/${fee}
- [ ] /transaction/await/${receipt}
- [ ] /transaction/list
- [ ] /transaction/list/${from}/${count}
- [ ] /transaction/status/${receipt}
- [ ] /unfreeze/${address}/${asset}/fee/${feeAddress}/${feeAmount}
- [ ] /unwrap/asset/${asset}/amount/${amount}/erc20/${erc20}
- [ ] /view/${asset}
- [ ] /view/key/${key}
- [ ] /wrap/destination/${destination}/ethaddress/${ethAddress}/amount/${amount}/asset/${asset}

Some are more complicated due to optional fields.
- [ ] /newasset/erc20/${erc20}/issuer/${issuer}
```javascript
  let url = `newasset/erc20/${erc20}/issuer/${issuer}`;
  if (traceKey) {
    url += `/tracekey/${traceKey}`;
  }
  if (freezeKey) {
    url += `/freezekey/${freezeKey}`;
  }
  if (traceAmount) {
    url += `/traceamount/${traceAmount}`;
  }
  if (traceAddress) {
    url += `/traceaddress/${traceAddress}`;
  }
  if (revealThreshold) {
    url += `/revealthreshold/${revealThreshold}`;
  }
  return serverRequest(url);
```

- [ ] /newasset/description/${description}
```javascript
  let url = `newasset/description/${description}`;
  if (traceKey) {
    url += `/tracekey/${traceKey}`;
  }
  if (freezeKey) {
    url += `/freezekey/${freezeKey}`;
  }
  if (traceAmount) {
    url += `/traceamount/${traceAmount}`;
  }
  if (traceAddress) {
    url += `/traceaddress/${traceAddress}`;
  }
  if (revealThreshold) {
    url += `/revealthreshold/${revealThreshold}`;
  }
  return serverRequest(url);
```

- [ ] /newasset
```javascript
  let url = 'newasset';
  if (traceKey) {
    url += `/tracekey/${traceKey}`;
  }
  if (freezeKey) {
    url += `/freezekey/${freezeKey}`;
  }
  if (traceAmount) {
    url += `/traceamount/${traceAmount}`;
  }
  if (traceAddress) {
    url += `/traceaddress/${traceAddress}`;
  }
  if (revealThreshold) {
    url += `/revealthreshold/${revealThreshold}`;
  }
  return serverRequest(url);
```

- [ ] /getinfo
```javascript
enum InfoType {
  Address = 'address',
  Key = 'key',
  Asset = 'asset',
  Freeze_Key = 'freezekey',
  Send_Key = 'sendkey',
  Trace_Key = 'tracekey',
}

export const getInfo = async (
  infoType?: InfoType,
  asset?: string,
): Promise<Response> => {
  let url = 'getinfo';
  if (infoType === InfoType.Address) {
    url = 'getinfo/address';
  } else if (infoType === InfoType.Key) {
    url = 'getinfo/key';
  } else if (infoType === InfoType.Asset && !asset) {
    url = 'getinfo/asset';
  } else if (infoType === InfoType.Asset && asset) {
    url = `getinfo/asset/${asset}`;
  } else if (infoType === InfoType.Freeze_Key) {
    url = 'getinfo/freezekey';
  } else if (infoType === InfoType.Send_Key) {
    url = 'getinfo/sendkey';
  } else if (infoType === InfoType.Trace_Key) {
    url = 'getinfo/tracekey';
  }
  return serverRequest(url);
};
```

**Comment by pictographer** [comment]
Currently adding integration test notes to [CAPE GUI Testing Backlog V1](https://www.notion.so/espressosys/CAPE-GUI-Testing-Backlog-V1-6bfd07d599c24fe58168ca91dacefe65)
