### ISSUE TITLE
Calls to sleep, unwrap, exit, panic and other functions that can mask fragile behavior have been reviewed

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#913]
The Rust code for the solidity contracts is only used for testing. So it is only needed to review the non test code for the CAPE services and the Wallet:

- [x] EQS
- [x] Address Book
- [x] Faucet
- [x] (Minimal) Relayer
- [x] Wallet

**Comment by pictographer** [comment]
- [ ] sleep
- [ ] unwrap
- [ ] exit
- [ ] panic

**Comment by pictographer** [comment]
The call to sleep in `cape/eqs/src/entry.rs` doesn't account for the time spent in `eth_poll.check().await`. This would only be a problem if the checking time is highly variable and we would want to adjust the sleep accordingly.

**Comment by nyospe** [comment]
No, this is intentional. The checking time may be variable, but check() clears the queue completely each time, and aside from the first time (loading from zero) on a long-running instance of the contract, it will always be significantly less than a single commit cycle, and the sleep time is intended to be less than (on the order of half of) the chain's commit cycle time. In the worst case scenario, we still always want that sleep, and we don't really benefit from subtracting off the time spent, since there should always be nearly as many no-work check calls as working check calls, even at the maximum rate. Adding the complexity of the subtraction is a potential source of defects, and premature at this time.

**Comment by pictographer** [comment]
Next time you're in there, this comment would be an excellent code comment. :-)

**Comment by pictographer** [comment]
Are the panics in `/cape/contracts/rust/src/ethereum.rs` function `load_contract` and `ensure_connected_to_contract` safe because they're only used in contract deployment and this is something that can't recover if it fails?

**Comment by pictographer** [comment]
@nyospe Atomic Store and its callers use `unwrap()` frequently. It's not obvious whether this is I/O error handling tech debt; or failing quickly is the best we can do. Do we need an issue or documentation?

**Comment by pictographer** [comment]
The Relayer's use of `unwrap` is probably the best we can do, unless we can come up with a way to avoid or recover from poisoned locks.

**Comment by pictographer** [comment]
```bash
~/tri/cape/wallet$ find . -name '*.rs' -exec cat \{} \;|fgrep -c 'unwrap('
458
```
Oh, my! ;-)
